/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: bc79da05726976fc1b77b054b5f0a57d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface ProductionEnv {
		AWS_REGION: "us-west-2";
		ENVIRONMENT: "production";
		VERSION: "@@VERSION@@";
		RETURN_STACK_TRACES: "false";
		DA_ORIGIN: "https://admin.da.live";
		AWS_BEARER_TOKEN_BEDROCK: string;
		DAADMIN: Fetcher /* da-admin */;
		DACOLLAB: Fetcher /* da-collab */;
	}
	interface DevEnv {
		AWS_REGION: "us-west-2";
		ENVIRONMENT: "dev";
		VERSION: "0.0.0-dev";
		RETURN_STACK_TRACES: "true";
		DA_ORIGIN: "http://localhost:8787";
		AWS_BEARER_TOKEN_BEDROCK: string;
		DAADMIN: Fetcher /* da-admin-local */;
		DACOLLAB: Fetcher /* da-collab-local */;
	}
	interface Env {
		AWS_BEARER_TOKEN_BEDROCK: string;
		AWS_REGION?: "us-west-2";
		ENVIRONMENT?: "production" | "dev";
		VERSION?: "@@VERSION@@" | "0.0.0-dev";
		RETURN_STACK_TRACES?: "false" | "true";
		DA_ORIGIN?: "https://admin.da.live" | "http://localhost:8787";
		DAADMIN?: Fetcher /* da-admin */ | Fetcher /* da-admin-local */;
		DACOLLAB?: Fetcher /* da-collab */ | Fetcher /* da-collab-local */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AWS_REGION" | "ENVIRONMENT" | "VERSION" | "RETURN_STACK_TRACES" | "DA_ORIGIN" | "AWS_BEARER_TOKEN_BEDROCK">> {}
}
