/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2b4f9fedc53d88fc103f78f4ce369946)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		DAADMIN: Fetcher /* da-admin-local */;
		AWS_BEARER_TOKEN_BEDROCK: string;
		AWS_REGION: string;
	}
}
interface Env extends Cloudflare.Env {}
